-- ====================================================================
-- TradIA - Esquema de Base de Datos para Supabase (PostgreSQL)
-- Copia y pega este contenido en el SQL Editor de tu proyecto Supabase.
-- ====================================================================

-- 1. Cartera y Wallet Virtual (Paper Trading)
CREATE TABLE IF NOT EXISTS sim_wallet (
    id INTEGER PRIMARY KEY DEFAULT 1,
    cash_balance NUMERIC NOT NULL,
    initial_balance NUMERIC NOT NULL,
    floor_activated BOOLEAN NOT NULL DEFAULT FALSE,
    is_halted BOOLEAN NOT NULL DEFAULT FALSE,
    halt_reason TEXT DEFAULT '',
    start_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Posiciones Abiertas Simuladas
CREATE TABLE IF NOT EXISTS sim_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT UNIQUE NOT NULL,
    qty NUMERIC NOT NULL,
    entry_price NUMERIC NOT NULL,
    entry_time TIMESTAMPTZ NOT NULL,
    entry_reasons JSONB NOT NULL DEFAULT '[]'::jsonb,
    entry_fee NUMERIC NOT NULL DEFAULT 0.0,
    position_cost_usdt NUMERIC NOT NULL
);

-- 3. Operaciones Simuladas Cerradas (Historial de Trades)
CREATE TABLE IF NOT EXISTS sim_trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    action TEXT NOT NULL DEFAULT 'BUY',
    entry_time TIMESTAMPTZ NOT NULL,
    exit_time TIMESTAMPTZ NOT NULL,
    entry_price NUMERIC NOT NULL,
    exit_price NUMERIC NOT NULL,
    qty NUMERIC NOT NULL,
    position_size_usdt NUMERIC NOT NULL,
    total_fees_usdt NUMERIC NOT NULL DEFAULT 0.0,
    gross_pnl_usdt NUMERIC NOT NULL,
    net_pnl_usdt NUMERIC NOT NULL,
    net_pnl_pct NUMERIC NOT NULL,
    entry_reasons JSONB NOT NULL DEFAULT '[]'::jsonb,
    exit_reasons JSONB NOT NULL DEFAULT '[]'::jsonb
);

-- 4. Instantáneas Diarias de Rendimiento
CREATE TABLE IF NOT EXISTS sim_daily_snapshots (
    date TEXT PRIMARY KEY,
    closing_balance NUMERIC NOT NULL,
    net_pnl_usdt NUMERIC NOT NULL,
    net_pnl_pct NUMERIC NOT NULL,
    trades_count INTEGER NOT NULL DEFAULT 0,
    win_rate_pct NUMERIC NOT NULL DEFAULT 0.0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. Registro de Señales Técnicas Generadas
CREATE TABLE IF NOT EXISTS signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL,
    symbol TEXT NOT NULL,
    action TEXT NOT NULL,
    price NUMERIC NOT NULL,
    score INTEGER NOT NULL,
    reasons JSONB NOT NULL DEFAULT '[]'::jsonb,
    metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. Registro de Posiciones Manuales del Usuario
CREATE TABLE IF NOT EXISTS user_confirmed_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    side TEXT NOT NULL DEFAULT 'BUY',
    entry_price NUMERIC NOT NULL,
    entry_time TIMESTAMPTZ NOT NULL,
    size_usdt NUMERIC,
    notes TEXT,
    is_open INTEGER NOT NULL DEFAULT 1,
    close_price NUMERIC,
    closed_at TIMESTAMPTZ
);

-- 7. Control de Estado Operativo y Franjas de Trading Remotas (Dashboard)
CREATE TABLE IF NOT EXISTS bot_control (
    id INTEGER PRIMARY KEY DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused_until', 'paused_indefinite')),
    resume_at TIMESTAMPTZ,
    trading_window_1_start TEXT NOT NULL DEFAULT '08:30',
    trading_window_1_end TEXT NOT NULL DEFAULT '17:30',
    trading_window_2_start TEXT NOT NULL DEFAULT '20:30',
    trading_window_2_end TEXT NOT NULL DEFAULT '23:00',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ====================================================================
-- SEGURIDAD: Row Level Security (RLS) & Supabase Auth
-- Solo usuarios autenticados mediante Supabase Auth pueden leer/escribir.
-- La clave 'service_role' (GitHub Actions) omite RLS automáticamente.
-- ====================================================================
ALTER TABLE bot_control ENABLE ROW LEVEL SECURITY;
ALTER TABLE sim_wallet ENABLE ROW LEVEL SECURITY;
ALTER TABLE sim_positions ENABLE ROW LEVEL SECURITY;
ALTER TABLE sim_trades ENABLE ROW LEVEL SECURITY;
ALTER TABLE sim_daily_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_confirmed_positions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users full access bot_control" ON bot_control;
CREATE POLICY "Authenticated users full access bot_control" ON bot_control FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users full access sim_wallet" ON sim_wallet;
CREATE POLICY "Authenticated users full access sim_wallet" ON sim_wallet FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users full access sim_positions" ON sim_positions;
CREATE POLICY "Authenticated users full access sim_positions" ON sim_positions FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users full access sim_trades" ON sim_trades;
CREATE POLICY "Authenticated users full access sim_trades" ON sim_trades FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users full access sim_daily_snapshots" ON sim_daily_snapshots;
CREATE POLICY "Authenticated users full access sim_daily_snapshots" ON sim_daily_snapshots FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users full access signals" ON signals;
CREATE POLICY "Authenticated users full access signals" ON signals FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users full access user_confirmed_positions" ON user_confirmed_positions;
CREATE POLICY "Authenticated users full access user_confirmed_positions" ON user_confirmed_positions FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Inicializar bot_control con estado activo y franjas por defecto si está vacío
INSERT INTO bot_control (id, status, resume_at, trading_window_1_start, trading_window_1_end, trading_window_2_start, trading_window_2_end, updated_at)
VALUES (1, 'active', NULL, '08:30', '17:30', '20:30', '23:00', NOW())
ON CONFLICT (id) DO NOTHING;

-- Inicializar wallet en 10.0€ si está vacío
INSERT INTO sim_wallet (id, cash_balance, initial_balance, floor_activated, is_halted, halt_reason, start_date, updated_at)
VALUES (1, 10.0, 10.0, FALSE, FALSE, '', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;
