-- ====================================================================
-- TradIA - Esquema de Base de Datos para Supabase (PostgreSQL)
-- Copia y pega este contenido en el SQL Editor de tu proyecto Supabase.
-- ====================================================================

-- 1. Cartera y Wallet Virtual (Paper Trading)
CREATE TABLE IF NOT EXISTS sim_wallet (
    id INTEGER PRIMARY KEY DEFAULT 1,
    cash_balance NUMERIC NOT NULL,
    initial_balance NUMERIC NOT NULL,
    floor_activated BOOLEAN NOT NULL DEFAULT FALSE,
    is_halted BOOLEAN NOT NULL DEFAULT FALSE,
    halt_reason TEXT DEFAULT '',
    start_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Posiciones Abiertas Simuladas
CREATE TABLE IF NOT EXISTS sim_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT UNIQUE NOT NULL,
    qty NUMERIC NOT NULL,
    entry_price NUMERIC NOT NULL,
    entry_time TIMESTAMPTZ NOT NULL,
    entry_reasons JSONB NOT NULL DEFAULT '[]'::jsonb,
    entry_fee NUMERIC NOT NULL DEFAULT 0.0,
    position_cost_usdt NUMERIC NOT NULL
);

-- 3. Operaciones Simuladas Cerradas (Historial de Trades)
CREATE TABLE IF NOT EXISTS sim_trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    action TEXT NOT NULL DEFAULT 'BUY',
    entry_time TIMESTAMPTZ NOT NULL,
    exit_time TIMESTAMPTZ NOT NULL,
    entry_price NUMERIC NOT NULL,
    exit_price NUMERIC NOT NULL,
    qty NUMERIC NOT NULL,
    position_size_usdt NUMERIC NOT NULL,
    total_fees_usdt NUMERIC NOT NULL DEFAULT 0.0,
    gross_pnl_usdt NUMERIC NOT NULL,
    net_pnl_usdt NUMERIC NOT NULL,
    net_pnl_pct NUMERIC NOT NULL,
    entry_reasons JSONB NOT NULL DEFAULT '[]'::jsonb,
    exit_reasons JSONB NOT NULL DEFAULT '[]'::jsonb
);

-- 4. Instantáneas Diarias de Rendimiento
CREATE TABLE IF NOT EXISTS sim_daily_snapshots (
    date TEXT PRIMARY KEY,
    closing_balance NUMERIC NOT NULL,
    net_pnl_usdt NUMERIC NOT NULL,
    net_pnl_pct NUMERIC NOT NULL,
    trades_count INTEGER NOT NULL DEFAULT 0,
    win_rate_pct NUMERIC NOT NULL DEFAULT 0.0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. Registro de Señales Técnicas Generadas
CREATE TABLE IF NOT EXISTS signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL,
    symbol TEXT NOT NULL,
    action TEXT NOT NULL,
    price NUMERIC NOT NULL,
    score INTEGER NOT NULL,
    reasons JSONB NOT NULL DEFAULT '[]'::jsonb,
    metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. Registro de Posiciones Manuales del Usuario
CREATE TABLE IF NOT EXISTS user_confirmed_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    side TEXT NOT NULL DEFAULT 'BUY',
    entry_price NUMERIC NOT NULL,
    entry_time TIMESTAMPTZ NOT NULL,
    size_usdt NUMERIC,
    notes TEXT,
    is_open INTEGER NOT NULL DEFAULT 1,
    close_price NUMERIC,
    closed_at TIMESTAMPTZ
);

-- Desactivar RLS o permitir acceso para que funcione con claves anon y service_role
ALTER TABLE sim_wallet DISABLE ROW LEVEL SECURITY;
ALTER TABLE sim_positions DISABLE ROW LEVEL SECURITY;
ALTER TABLE sim_trades DISABLE ROW LEVEL SECURITY;
ALTER TABLE sim_daily_snapshots DISABLE ROW LEVEL SECURITY;
ALTER TABLE signals DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_confirmed_positions DISABLE ROW LEVEL SECURITY;

-- Inicializar wallet en 10.0€ si está vacío
INSERT INTO sim_wallet (id, cash_balance, initial_balance, floor_activated, is_halted, halt_reason, start_date, updated_at)
VALUES (1, 10.0, 10.0, FALSE, FALSE, '', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;
